### ISSUE TITLE
security group and subnet IP are not passed to the module?

### ISSUE THREAD

**Issue by nbmustafa** [JamesWoolfenden/terraform-aws-lex-lambda#5]
Hi
Excellent work by the way. but I noticed security group and subnet IP are not passed to the module? is that because you are keeping it as optional ? since in the var you have set default as [] if passed will take the value if not will keep it as placeholder?

variable subnet_ids {
  description = "Subnet IDs..."
  type        = list(string)
  default     = []
}

**Comment by JamesWoolfenden** [comment]
yes its optional.
